spring:
  application:
    name: skillbridge-ai
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:skillbridge;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:skillbridge;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""

---
spring:
  config:
    activate:
      on-profile: prod-mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skillbridge?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

---
spring:
  config:
    activate:
      on-profile: prod-oracle
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: SKILLBRIDGE
    password: SKILLBRIDGE